# Generated by Django 3.1.7 on 2021-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloz',
            fields=[
                ('kod07', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Bloz')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('dawka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dawka')),
                ('opakh', models.CharField(blank=True, max_length=40, null=True, verbose_name='Opakowanie')),
                ('prodc', models.CharField(blank=True, max_length=60, null=True, verbose_name='Producent')),
                ('kodkr', models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN')),
            ],
            options={
                'db_table': 'BLOZ',
                'managed': False,
            },
        ),
    ]
