# Generated by Django 3.1.7 on 2021-04-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210324_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozycje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cenaz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cena_zak')),
                ('uwagi', models.TextField(blank=True, max_length=300, null=True, verbose_name='Uwagi')),
                ('akt', models.DateTimeField(auto_now=True, verbose_name='Akt')),
                ('apteka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.apteki')),
                ('bloz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bloz')),
            ],
        ),
    ]
