# Generated by Django 3.1.7 on 2021-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pozycje'),
    ]

    operations = [
        migrations.AddField(
            model_name='apteki',
            name='aktywna',
            field=models.BooleanField(default=1, max_length=1, verbose_name='Aktywna'),
        ),
    ]
